name: CI

on:
  push:
    branches: [master]
    tags: [ "v*" ]
  pull_request:
    branches: [master]

jobs:
  lint-vet-build-test:
    name: Lint, Vet, Build, Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install Dependencies
      run: make install
    
    - name: Lint Go Code
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest

    - name: Vet Go Code
      run: make vet
    
    - name: Run Tests and Generate Coverage
      run: make coverage
    
    - name: Build
      run: make build

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
